name: build
on: [pull_request, push, workflow_dispatch]

jobs:
    build:
        strategy:
            matrix:
                # Use these Java versions
                java: 
                   - 19 # Current Java LTS & minimum supported by Minecraft
                # and run on both Linux and Windows
                os: [macos-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: validate gradle wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: setup jdk ${{ matrix.java }}
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.java }}
                  distribution: zulu
            - name: Build with Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew build
            - name: capture build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Artifacts
                  path: build/libs/
